#!/usr/bin/env python3
"""Emit the paper's GSR tables: one twenty-row results table plus its supplement.

Writes two complete table environments (no empty cells anywhere) to the
paper tree:

  sections/gsr_table_full.tex       tab:gsr_results, \\input{} by 02_results.tex:
                                    every half of all ten matches, scored at
                                    match length (GS-HOTA, DetA, AssA, LocA,
                                    attrs off) and on its opening 30 s
                                    (GS-HOTA, attrs off), one row per half,
                                    with a mean over all twenty halves and a
                                    mean over the released test split.
  sections/gsr_attrs_off_table.tex  tab:gsr_attrs_off, \\input{} by
                                    05_supplementary.tex (Supplementary Table 1):
                                    attributes-off DetA/AssA/LocA at both
                                    lengths, so that every attrs-off component
                                    quoted in the prose has a display item.

Both regenerate with one command whenever a score file changes:

    python3 scripts/gsr/emit_combined_gsr_table.py

30 s scores come from results/gsr/sweep30s_all_matches.csv (first 750 frames
of every half, one configuration: the adapted pipeline with the weights the
baseline ships, per-detection team assignment) and, for the attrs-off
components, from results/gsr/score_30s_<match>_<half>.json. Full-half scores
are collected with the same source preference as compile_full_table.py
(fleet1 > fleet2 > gsr4 > local); the cloud halves are read from the versioned
copies under results/gsr/cloud/ so that every input is in the repo. All
twenty halves are required to be present: the table has no dash cells (the
author's decision of 2026-09-08 is that a gapped table "looks unfinished").

Every count and hardware statement in the captions is derived from the rows
and each row's source tag ("local" is the workstation, "fleet1"/"fleet2"/
"gsr4" the cloud L4 instances, HYBRID_HALVES the halves whose detection and
pose ran on the cloud before the workstation resumed), so a regenerated table
cannot leave a caption contradicting its body.
"""

import csv
import json
import re
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

from compile_full_table import MATCHES, HALVES, collect

REPO = Path(__file__).resolve().parents[2]
SWEEP_CSV = REPO / "results" / "gsr" / "sweep30s_all_matches.csv"
SCORE30_DIR = REPO / "results" / "gsr"
CLOUD_MOUNT_ROOT = Path("/mnt/storage/SoccerTrack-v2/gsr-cloud-results")
CLOUD_LOCAL_ROOT = REPO / "results" / "gsr" / "cloud"
PAPER_SECTIONS = Path("/home/atom/soccertrack-v2/paper/sections")
OUT_FULL_TEX = PAPER_SECTIONS / "gsr_table_full.tex"
OUT_OFF_TEX = PAPER_SECTIONS / "gsr_attrs_off_table.tex"
PREFIX_CSV = REPO / "results" / "gsr" / "prefix_rescoring_all_halves.csv"
OUT_PREFIX_TEX = PAPER_SECTIONS / "gsr_prefix_table.tex"

TEST_MATCHES = ["128057", "132831"]
FULL_METRICS = ["hota", "deta", "assa", "loca", "off_hota"]
OFF_METRICS = ["off_deta", "off_assa", "off_loca"]
OFF_KEY = "attributes OFF (geometry + association)"
ON_KEY = "attributes ON (official GS-HOTA)"

HEADER = [
    "% GENERATED by scripts/gsr/emit_combined_gsr_table.py in the",
    "% SoccerTrack-v2 code repo. Do not edit by hand; rerun the script",
    "% when further full-half results land.",
]


NUMBER_WORDS = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five",
                6: "six", 7: "seven", 8: "eight", 9: "nine", 10: "ten",
                11: "eleven", 12: "twelve", 13: "thirteen", 14: "fourteen",
                15: "fifteen", 16: "sixteen", 17: "seventeen", 18: "eighteen",
                19: "nineteen", 20: "twenty"}
HALF_WORDS = {"1st": "first", "2nd": "second"}


def words(n):
    return NUMBER_WORDS.get(n, str(n))


def describe_halves(pairs):
    """'both halves of 128057 and the first half of 132831' for a list of
    (match, half) pairs, grouped by match in the order given."""
    by_match = {}
    for m, h in pairs:
        by_match.setdefault(m, []).append(h)
    parts = []
    for m, hs in by_match.items():
        if len(hs) == 2:
            parts.append(f"both halves of {m}")
        else:
            parts.append(f"the {HALF_WORDS[hs[0]]} half of {m}")
    if len(parts) <= 1:
        return "".join(parts)
    return ", ".join(parts[:-1]) + " and " + parts[-1]


def mark(match):
    return r"$^\dagger$" if match in TEST_MATCHES else ""


def r2(x):
    """Two decimals, rounded half-up on the decimal repr: cloud scorers store
    three decimals, so ties such as 82.735 are real and must not fall to
    binary half-even."""
    return str(Decimal(repr(float(x))).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP))


def fmt(values):
    return " & ".join(r2(x) for x in values)


def mean(rows, key):
    return sum(r[key] for r in rows) / len(rows)


def load_sweep():
    """(match, half) -> (official GS-HOTA, attrs-off GS-HOTA) on the first 30 s."""
    sweep = {}
    with open(SWEEP_CSV) as f:
        for row in csv.DictReader(f):
            sweep[(row["match"], row["half"])] = (
                float(row["gshota_official"]), float(row["gshota_attrs_off"]))
    return sweep


def load_off30():
    """(match, half) -> (DetA, AssA, LocA) with attributes off on the first 30 s."""
    off30 = {}
    for m in MATCHES:
        for h in HALVES:
            with open(SCORE30_DIR / f"score_30s_{m}_{h}.json") as f:
                scores = json.load(f)["scores"]
            s, on = scores[OFF_KEY], scores[ON_KEY]
            off30[(m, h)] = (s["DetA"], s["AssA"], s["LocA"], on["ids"], on["gt_ids"])
    return off30


def load_full():
    """(match, half) -> score dict for every half with a completed run."""
    full = {}
    for m in MATCHES:
        for h in HALVES:
            src = collect(m, h)
            for pref in ("fleet1", "fleet2", "gsr4", "local"):
                if pref in src:
                    full[(m, h)] = dict(src[pref], source=pref)
                    break
    missing_test = [(m, h) for m in TEST_MATCHES for h in HALVES
                    if (m, h) not in full]
    assert not missing_test, f"released test split incomplete: {missing_test}"
    return full


def tracklets(row):
    """(predicted tracklets, annotated identities) of a full-half run: the
    scorer's ids / gt_ids for a local score JSON, or the "N predicted
    tracklets vs M real players" line of the score.log beside a cloud
    zscore.json."""
    path = Path(row["path"])
    if row["source"] == "local":
        with open(path) as f:
            on = json.load(f)["scores"][ON_KEY]
        return int(on["ids"]), int(on["gt_ids"])
    for cand in (path.parent / "score.log",
                 CLOUD_LOCAL_ROOT / path.parent.relative_to(CLOUD_MOUNT_ROOT) / "score.log"
                 if str(path).startswith(str(CLOUD_MOUNT_ROOT)) else None):
        if cand and cand.exists():
            m = re.findall(r"(\d+) predicted tracklets vs (\d+) real players", cand.read_text(errors="replace"))
            if m:
                return int(m[-1][0]), int(m[-1][1])
    raise SystemExit(f"no tracklet count for {row['path']}")


def rescored_132831_first(full):
    """True while the 132831 first-half row is the local pred-shift rescoring
    (source 'local'); a completed cloud rerun staged with the measured offset
    would replace it and the rescoring sentence must then disappear."""
    return full[("132831", "1st")]["source"] == "local"


# Halves whose score file lives in results/gsr (source tag "local") but whose
# detection and pose stages ran on a cloud L4 instance, the workstation
# resuming the remaining modules from that checkpoint. Provenance only: the
# caption states where each stage ran, nothing about attempts.
HYBRID_HALVES = {("117092", "1st")}


def hardware_sentence(full, rows):
    """Where each row ran, from the source tag of each row (plus the hybrid
    list above) rather than from a hard-coded description."""
    local = [k for k in rows if full[k]["source"] == "local" and k not in HYBRID_HALVES]
    hybrid = [k for k in rows if full[k]["source"] == "local" and k in HYBRID_HALVES]
    cloud = [k for k in rows if full[k]["source"] != "local"]
    parts = []
    if local:
        ws = describe_halves(local)
        parts.append(f"{ws[0].upper() + ws[1:]} were run on a workstation GPU")
    if hybrid:
        parts.append(f"for {describe_halves(hybrid)}, detection and pose"
                     " estimation were run on a cloud L4 instance and the"
                     " remaining modules on the workstation from that checkpoint")
    if cloud:
        other = ("the other half" if len(cloud) == 1
                 else f"the {words(len(cloud))} other halves")
        if not (local or hybrid):
            other = f"all {words(len(cloud))} halves"
        parts.append(f"{other} were run on cloud L4 GPUs")
    sentence = "; ".join(parts) + "."
    if cloud or hybrid:
        sentence += (" Every cloud pose stage used half-precision pose"
                     " estimation, validated to three decimals against single"
                     " precision on a 30-second clip (Methods).")
    return sentence[0].upper() + sentence[1:]


def rescoring_sentence(full):
    if not rescored_132831_first(full):
        return ""
    return (" The 132831 first-half row is rescored from the saved"
            " predictions after correcting a staging-time temporal offset;"
            " the residual misalignment is at most 5 frames ($0.2$\\,s),"
            " which displaces a player running at $5$\\,m/s by about"
            " $1$\\,m, well under the $5$\\,m tolerance.")


def wrap_caption(text, indent="  ", width=72):
    """Break a caption into lines of the emitted file's house width."""
    out, line = [], indent
    for word in text.split():
        if len(line) + len(word) + 1 > width and line.strip():
            out.append(line.rstrip())
            line = indent
        line += word + " "
    if line.strip():
        out.append(line.rstrip())
    return out


def emit_combined(sweep, full):
    """One row per half, match order: 30 s (GS-HOTA, attrs off) then the full
    half (GS-HOTA, DetA, AssA, LocA, attrs off)."""
    rows = [(m, h) for m in MATCHES for h in HALVES]
    missing = [k for k in rows if k not in full or k not in sweep]
    if missing:
        raise SystemExit(f"table would have gaps; missing full or 30 s scores for {missing}")
    test = [k for k in rows if k[0] in TEST_MATCHES]
    n_all, n_test = len(rows), len(test)
    mean30 = [sum(sweep[k][i] for k in rows) / n_all for i in (0, 1)]
    mean30_test = [sum(sweep[k][i] for k in test) / n_test for i in (0, 1)]
    all_rows = [full[k] for k in rows]
    test_rows = [full[k] for k in test]
    caption = (
        r"\caption{Game state reconstruction on all " + words(n_all) + " halves,"
        " each run and scored over the whole half and, independently, on its"
        " opening 30 seconds, the clip length of the SoccerNet-GSR benchmark:"
        " the SoccerNet"
        r" pipeline of Section~\ref{subsec:methods_gsr}, adapted by the authors"
        " on released footage that includes a test-split half, with no"
        " component's weights trained on SoccerTrack v2, run end to end under"
        " one configuration, the per-detection team assignment. GS-HOTA is the"
        " official metric, which classes detections by (role, team, jersey);"
        " DetA, AssA and LocA are its detection, association and localisation"
        r" components; \emph{Attrs off} rescores the same predictions with"
        " attribute matching disabled, so that only geometry and association"
        " count (components in Supplementary"
        r" Table~\ref{tab:gsr_attrs_off}). The test split of the released"
        r" match-level split is marked $\dagger$. Means are per column,"
        " computed from unrounded scores. Where each half was run is"
        r" recorded in Section~\ref{subsec:methods_scale}.}")
    # hardware_sentence(full, rows) is kept for the console record: the
    # caption no longer carries it (reviewer request, 2026-09-14), Methods does.
    print("hardware: " + hardware_sentence(full, rows))
    lines = HEADER + [
        r"\begin{table}[!htbp]",
        r"  \centering",
    ] + wrap_caption(caption) + [
        r"  \label{tab:gsr_results}",
        r"  \footnotesize",
        r"  \setlength{\tabcolsep}{4pt}",
        r"  \begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}lrrrrrrr@{}}",
        r"    \toprule",
        r"    & \multicolumn{2}{c}{Opening 30\,s} & \multicolumn{5}{c}{Full half (45\,min)} \\",
        r"    \cmidrule(lr){2-3} \cmidrule(l){4-8}",
        r"    Half & GS-HOTA & Attrs off & GS-HOTA & DetA & AssA & LocA & Attrs off \\",
        r"    \midrule",
    ]
    for m, h in rows:
        s30 = sweep[(m, h)]
        lines.append(f"    {m}, {h}{mark(m)} & "
                     + fmt([s30[0], s30[1]] + [full[(m, h)][k] for k in FULL_METRICS])
                     + r" \\")
    lines += [
        r"    \midrule",
        f"    Mean, all {words(n_all)} halves & "
        + fmt(mean30 + [mean(all_rows, k) for k in FULL_METRICS]) + r" \\",
        r"    Mean, test split$^\dagger$ & "
        + fmt(mean30_test + [mean(test_rows, k) for k in FULL_METRICS]) + r" \\",
        r"    \bottomrule",
        r"  \end{tabular*}",
        r"\end{table}",
    ]
    OUT_FULL_TEX.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_FULL_TEX}  ({n_all} halves, {n_test} in the test split)")
    print(f"30s means: official {mean30[0]:.2f}, attrs-off {mean30[1]:.2f}"
          f" (test split {mean30_test[0]:.2f} / {mean30_test[1]:.2f})")
    print(f"all-{n_all} full means: " + ", ".join(
        f"{k}={mean(all_rows, k):.2f}" for k in FULL_METRICS))
    print("test-split full means: " + ", ".join(
        f"{k}={mean(test_rows, k):.2f}" for k in FULL_METRICS))
    for m, h in rows:
        sc = full[(m, h)]
        print(f"  full {m}-{h}: {sc['hota']:.2f} ({sc['source']}, "
              f"{Path(sc['path']).relative_to(REPO) if sc['path'].startswith(str(REPO)) else sc['path']})")


def emit_attrs_off(off30, full):
    order = [(m, h) for m in MATCHES for h in HALVES if (m, h) in full]
    n30 = len(off30)
    full_rows = [full[k] for k in order]
    nfull = len(full_rows)
    mean_off30 = [sum(v[i] for v in off30.values()) / n30 for i in range(3)]
    trk = {k: tracklets(full[k]) for k in order}
    mean_offfull = [mean(full_rows, k) for k in OFF_METRICS]
    complete = nfull == n30
    lower_block_phrase = ("the full half of the same halves" if complete
                          else "the match-length evaluation set")
    lower_block_header = (f"Full half (45\\,min), all {words(nfull)} halves" if complete
                          else "Full half (45\\,min), match-length evaluation set")
    rescoring = (" the 132831 first-half match-length row is the rescoring"
                 r" described in Table~\ref{tab:gsr_results};"
                 if rescored_132831_first(full) else "")
    caption = (
        r"\caption{Components of the attributes-off scores of"
        r" Table~\ref{tab:gsr_results}: the same"
        " predictions rescored with attribute matching disabled, so that DetA,"
        " AssA and LocA measure geometry and association alone;"
        r" \emph{Tracklets} is the number of predicted identities and"
        r" \emph{Identities} the number of annotated identities in the"
        " sequence, substitutes included. The upper"
        " block is the opening 30 seconds of every half; the lower block is"
        f" {lower_block_phrase}. Configuration is as in that"
        f" table;{rescoring} the released test split is marked $\\dagger$."
        " Means are per column within each block, computed from unrounded"
        " scores.}")
    lines = HEADER + [
        r"\begin{table}[!htbp]",
        r"  \centering",
    ] + wrap_caption(caption) + [
        r"  \label{tab:gsr_attrs_off}",
        r"  \footnotesize",
        r"  \begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}lrrrrr@{}}",
        r"    \toprule",
        r"    Half & DetA & AssA & LocA & Tracklets & Identities \\",
        r"    \midrule",
        f"    \\multicolumn{{6}}{{@{{}}l}}{{\\emph{{First 30\\,s, all {words(n30)} halves}}}} \\\\",
    ]
    for m in MATCHES:
        for h in HALVES:
            v = off30[(m, h)]
            lines.append(f"    {m}, {h}{mark(m)} & " + fmt(v[:3]) + f" & {v[3]} & {v[4]}" + r" \\")
    lines += [
        f"    Mean, all {words(n30)} halves & " + fmt(mean_off30) + r" & & \\",
        r"    \midrule",
        f"    \\multicolumn{{6}}{{@{{}}l}}{{\\emph{{{lower_block_header}}}}} \\\\",
    ]
    for m, h in order:
        lines.append(f"    {m}, {h}{mark(m)} & "
                     + fmt([full[(m, h)][k] for k in OFF_METRICS])
                     + f" & {trk[(m, h)][0]} & {trk[(m, h)][1]}" + r" \\")
    lines += [
        f"    Mean, all {words(nfull)} halves & " + fmt(mean_offfull) + r" & & \\",
        r"    \bottomrule",
        r"  \end{tabular*}",
        r"\end{table}",
    ]
    OUT_OFF_TEX.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_OFF_TEX}")
    print("30s attrs-off means: " + ", ".join(
        f"{k}={v:.2f}" for k, v in zip(("deta", "assa", "loca"), mean_off30)))
    print("full attrs-off means: " + ", ".join(
        f"{k}={v:.2f}" for k, v in zip(OFF_METRICS, mean_offfull)))


WINDOW_LABELS = ["30s", "1min", "2min", "5min", "10min", "20min", "full"]
WINDOW_HEADS = ["30\\,s", "1\\,min", "2\\,min", "5\\,min", "10\\,min", "20\\,min", "Whole half"]


def emit_prefix_table():
    """Supplementary table: every whole-half run scored over growing windows
    from kickoff (compile_prefix_rescoring.py), official and attributes off."""
    rows = list(csv.DictReader(open(PREFIX_CSV)))
    order = [(m, h) for m in MATCHES for h in HALVES]
    val = {}
    for r in rows:
        val[(r["match"], r["half"], r["label"])] = (float(r["hota"]), float(r["off_hota"]))
    missing = [(m, h, l) for m, h in order for l in WINDOW_LABELS if (m, h, l) not in val]
    if missing:
        raise SystemExit(f"prefix table would have gaps: {missing[:5]}")
    n = len(order)
    caption = (
        r"\caption{GS-HOTA of the whole-half predictions of"
        r" Table~\ref{tab:gsr_results} scored over growing windows from"
        " kickoff: the first 30 seconds, 1, 2, 5, 10 and 20 minutes, and the"
        " whole half (Methods). The predictions are fixed and only the scored"
        " window changes, so the last column reproduces"
        r" Table~\ref{tab:gsr_results}. The upper block is the official"
        " metric, the lower block the same windows with attribute matching"
        " disabled. Means are per column, computed from unrounded scores; the"
        r" released test split is marked $\dagger$.}")
    lines = HEADER + [
        r"\begin{table}[!htbp]",
        r"  \centering",
    ] + wrap_caption(caption) + [
        r"  \label{tab:gsr_windows}",
        r"  \footnotesize",
        r"  \setlength{\tabcolsep}{4pt}",
        r"  \begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}lrrrrrrr@{}}",
        r"    \toprule",
        "    Half & " + " & ".join(WINDOW_HEADS) + r" \\",
        r"    \midrule",
    ]
    for idx, name in ((0, "Official GS-HOTA"), (1, "Attribute matching disabled")):
        if idx == 1:
            lines.append(r"    \midrule")
        lines.append(f"    \\multicolumn{{8}}{{@{{}}l}}{{\\emph{{{name}}}}} \\\\")
        for m, h in order:
            lines.append(f"    {m}, {h}{mark(m)} & "
                         + fmt([val[(m, h, l)][idx] for l in WINDOW_LABELS]) + r" \\")
        lines.append(f"    Mean, all {words(n)} halves & "
                     + fmt([sum(val[(m, h, l)][idx] for m, h in order) / n for l in WINDOW_LABELS])
                     + r" \\")
    lines += [
        r"    \bottomrule",
        r"  \end{tabular*}",
        r"\end{table}",
    ]
    OUT_PREFIX_TEX.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_PREFIX_TEX}  ({n} halves x {len(WINDOW_LABELS)} windows)")
    for idx, name in ((0, "official"), (1, "attrs-off")):
        print(f"window means {name}: " + ", ".join(
            f"{l}={sum(val[(m, h, l)][idx] for m, h in order) / n:.2f}" for l in WINDOW_LABELS))


def main():
    sweep = load_sweep()
    full = load_full()
    off30 = load_off30()
    emit_combined(sweep, full)
    emit_attrs_off(off30, full)
    emit_prefix_table()


if __name__ == "__main__":
    main()
