#!/usr/bin/env python3
"""Emit the paper's GSR tables: the two-tier evaluation plus its supplement.

Writes three complete table environments (no empty cells anywhere) to the
paper tree:

  sections/gsr_table_30s.tex        tab:gsr_30s, \\input{} by 02_results.tex
                                    Tier 1: the opening 30 s of every half of
                                    all ten matches, one row per match.
  sections/gsr_table_full.tex       tab:gsr_results, \\input{} by 02_results.tex
                                    Tier 2: the match-length (45 min) evaluation
                                    set, the four halves of the released test
                                    split plus the five further halves whose
                                    runs the compute budget allowed.
  sections/gsr_attrs_off_table.tex  tab:gsr_attrs_off, \\input{} by
                                    05_supplementary.tex (Supplementary Table 1):
                                    attributes-off DetA/AssA/LocA for both
                                    tiers, so that every attrs-off component
                                    quoted in the prose has a display item.

All three regenerate with one command as further full halves land:

    python3 scripts/gsr/emit_combined_gsr_table.py

30 s scores come from results/gsr/sweep30s_all_matches.csv (first 750 frames
of every half, one configuration: the adapted pipeline with the weights the
baseline ships, per-detection team assignment) and, for the attrs-off
components, from results/gsr/score_30s_<match>_<half>.json. Full-half scores
are collected with the same source preference as compile_full_table.py
(fleet1 > fleet2 > local). The full-length tables list only halves with a
completed run; the author's decision (2026-09-08) is that a gapped table
"looks unfinished", so no dash cells are emitted.
"""

import csv
import json
from pathlib import Path

from compile_full_table import MATCHES, HALVES, collect

REPO = Path(__file__).resolve().parents[2]
SWEEP_CSV = REPO / "results" / "gsr" / "sweep30s_all_matches.csv"
SCORE30_DIR = REPO / "results" / "gsr"
PAPER_SECTIONS = Path("/home/atom/soccertrack-v2/paper/sections")
OUT_30S_TEX = PAPER_SECTIONS / "gsr_table_30s.tex"
OUT_FULL_TEX = PAPER_SECTIONS / "gsr_table_full.tex"
OUT_OFF_TEX = PAPER_SECTIONS / "gsr_attrs_off_table.tex"

TEST_MATCHES = ["128057", "132831"]
FULL_METRICS = ["hota", "deta", "assa", "loca", "off_hota"]
OFF_METRICS = ["off_deta", "off_assa", "off_loca"]
OFF_KEY = "attributes OFF (geometry + association)"

HEADER = [
    "% GENERATED by scripts/gsr/emit_combined_gsr_table.py in the",
    "% SoccerTrack-v2 code repo. Do not edit by hand; rerun the script",
    "% when further full-half results land.",
]


def mark(match):
    return r"$^\dagger$" if match in TEST_MATCHES else ""


def fmt(values):
    return " & ".join(f"{x:.2f}" for x in values)


def mean(rows, key):
    return sum(r[key] for r in rows) / len(rows)


def load_sweep():
    """(match, half) -> (official GS-HOTA, attrs-off GS-HOTA) on the first 30 s."""
    sweep = {}
    with open(SWEEP_CSV) as f:
        for row in csv.DictReader(f):
            sweep[(row["match"], row["half"])] = (
                float(row["gshota_official"]), float(row["gshota_attrs_off"]))
    return sweep


def load_off30():
    """(match, half) -> (DetA, AssA, LocA) with attributes off on the first 30 s."""
    off30 = {}
    for m in MATCHES:
        for h in HALVES:
            with open(SCORE30_DIR / f"score_30s_{m}_{h}.json") as f:
                s = json.load(f)["scores"][OFF_KEY]
            off30[(m, h)] = (s["DetA"], s["AssA"], s["LocA"])
    return off30


def load_full():
    """(match, half) -> score dict for every half with a completed run."""
    full = {}
    for m in MATCHES:
        for h in HALVES:
            src = collect(m, h)
            for pref in ("fleet1", "fleet2", "local"):
                if pref in src:
                    full[(m, h)] = src[pref]
                    break
    return full


def full_row_order(full):
    """Test split first, then the additional halves, each in match order."""
    test = [(m, h) for m in TEST_MATCHES for h in HALVES if (m, h) in full]
    extra = [(m, h) for m in MATCHES for h in HALVES
             if (m, h) in full and m not in TEST_MATCHES]
    return test, extra


def emit_30s(sweep):
    n = len(sweep)
    mean30 = [sum(v[i] for v in sweep.values()) / n for i in (0, 1)]
    lines = HEADER + [
        r"\begin{table}[!htbp]",
        r"  \centering",
        r"  \caption{Game state reconstruction on the opening 30 seconds of",
        r"  every half of all ten matches, the clip length of the",
        r"  SoccerNet-GSR benchmark, run with the SoccerNet pipeline of",
        r"  Section~\ref{subsec:methods_gsr} as adapted by the authors on",
        r"  released footage, with no component trained on SoccerTrack v2,",
        r"  under one configuration, the per-detection team assignment.",
        r"  GS-HOTA is the official metric, which classes detections by",
        r"  (role, team, jersey); \emph{Attrs off} rescores the same",
        r"  predictions with attribute matching disabled, so that only",
        r"  geometry and association count (its components are listed in",
        r"  Supplementary Table~\ref{tab:gsr_attrs_off}). The released test",
        r"  split of the match-level split is marked $\dagger$. The mean is",
        r"  over all twenty halves, computed from unrounded scores.}",
        r"  \label{tab:gsr_30s}",
        r"  \small",
        r"  \begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}lrrrr@{}}",
        r"    \toprule",
        r"    & \multicolumn{2}{c}{GS-HOTA} & \multicolumn{2}{c}{Attrs off} \\",
        r"    \cmidrule(lr){2-3} \cmidrule(l){4-5}",
        r"    Match & 1st half & 2nd half & 1st half & 2nd half \\",
        r"    \midrule",
    ]
    for m in MATCHES:
        s1, s2 = sweep[(m, "1st")], sweep[(m, "2nd")]
        lines.append(f"    {m}{mark(m)} & " + fmt([s1[0], s2[0], s1[1], s2[1]])
                     + r" \\")
    lines += [
        r"    \midrule",
        f"    Mean, all twenty halves & \\multicolumn{{2}}{{c}}{{{mean30[0]:.2f}}}"
        f" & \\multicolumn{{2}}{{c}}{{{mean30[1]:.2f}}} \\\\",
        r"    \bottomrule",
        r"  \end{tabular*}",
        r"\end{table}",
    ]
    OUT_30S_TEX.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_30S_TEX}  ({n} halves)")
    print(f"30s means: official {mean30[0]:.2f}, attrs-off {mean30[1]:.2f}")
    return mean30


def emit_full(full):
    test, extra = full_row_order(full)
    test_rows = [full[k] for k in test]
    all_rows = [full[k] for k in test + extra]
    lines = HEADER + [
        r"\begin{table}[!htbp]",
        r"  \centering",
        r"  \caption{Game state reconstruction on the match-length (45-minute)",
        r"  evaluation set: the four halves of the released test split of the",
        r"  match-level split (marked $\dagger$) and five further halves that",
        r"  the compute budget allowed (Section~\ref{subsec:methods_scale}),",
        r"  run end to end with the adapted pipeline of",
        r"  Table~\ref{tab:gsr_30s} under the same configuration. The 132831",
        r"  first-half row is rescored from the saved predictions after",
        r"  correcting a staging-time temporal offset; the residual",
        r"  misalignment is at most 5 frames ($0.2$\,s), well under the",
        r"  $5$\,m tolerance. DetA, AssA and LocA are the detection,",
        r"  association and localisation components of the official GS-HOTA,",
        r"  which classes detections by (role, team, jersey); \emph{Attrs off}",
        r"  rescores the same predictions with attribute matching disabled,",
        r"  so that only geometry and association count (its components are",
        r"  listed in Supplementary Table~\ref{tab:gsr_attrs_off}). Means are",
        r"  per column, computed from unrounded scores. Both halves of 128057",
        r"  and the first half of 132831 were run on a workstation GPU; the",
        r"  six other halves were run on cloud L4 GPUs with half-precision",
        r"  pose estimation, validated to three decimals against",
        r"  single precision on a 30-second clip (Methods).}",
        r"  \label{tab:gsr_results}",
        r"  \small",
        r"  \begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}lrrrrr@{}}",
        r"    \toprule",
        r"    Half & GS-HOTA & DetA & AssA & LocA & Attrs off \\",
        r"    \midrule",
        r"    \multicolumn{6}{@{}l}{\emph{Test split}} \\",
    ]
    for m, h in test:
        lines.append(f"    {m}, {h}{mark(m)} & "
                     + fmt([full[(m, h)][k] for k in FULL_METRICS]) + r" \\")
    lines.append(r"    \midrule")
    lines.append(r"    \multicolumn{6}{@{}l}{\emph{Additional halves}} \\")
    for m, h in extra:
        lines.append(f"    {m}, {h}{mark(m)} & "
                     + fmt([full[(m, h)][k] for k in FULL_METRICS]) + r" \\")
    lines += [
        r"    \midrule",
        "    Mean, test split & "
        + fmt([mean(test_rows, k) for k in FULL_METRICS]) + r" \\",
        f"    Mean, all {NUMBER_WORDS.get(len(all_rows), len(all_rows))} & "
        + fmt([mean(all_rows, k) for k in FULL_METRICS]) + r" \\",
        r"    \bottomrule",
        r"  \end{tabular*}",
        r"\end{table}",
    ]
    OUT_FULL_TEX.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_FULL_TEX}  ({len(test)} test + {len(extra)} additional halves)")
    print("test-split means: " + ", ".join(
        f"{k}={mean(test_rows, k):.2f}" for k in FULL_METRICS))
    print(f"all-{len(all_rows)} means: " + ", ".join(
        f"{k}={mean(all_rows, k):.2f}" for k in FULL_METRICS))
    for (m, h) in test + extra:
        s = full[(m, h)]
        print(f"  full {m}-{h}: {s['hota']:.2f} (src {s['path'].split('/')[-2]})")


NUMBER_WORDS = {4: "four", 5: "five", 6: "six", 7: "seven", 8: "eight",
                9: "nine", 10: "ten", 11: "eleven", 12: "twelve",
                13: "thirteen", 14: "fourteen", 15: "fifteen", 16: "sixteen",
                17: "seventeen", 18: "eighteen", 19: "nineteen", 20: "twenty"}


def emit_attrs_off(off30, full):
    test, extra = full_row_order(full)
    n30 = len(off30)
    full_rows = [full[k] for k in test + extra]
    nfull = len(full_rows)
    mean_off30 = [sum(v[i] for v in off30.values()) / n30 for i in range(3)]
    mean_offfull = [mean(full_rows, k) for k in OFF_METRICS]
    lines = HEADER + [
        r"\begin{table}[!htbp]",
        r"  \centering",
        r"  \caption{Components of the attributes-off scores of",
        r"  Tables~\ref{tab:gsr_30s} and~\ref{tab:gsr_results}: the same",
        r"  predictions rescored with attribute matching disabled, so that",
        r"  DetA, AssA and LocA measure geometry and association alone. The",
        r"  upper block is the opening 30 seconds of every half; the lower",
        r"  block is the match-length evaluation set. Configuration and the",
        r"  132831 first-half rescoring are as in those tables; the released",
        r"  test split is marked $\dagger$. Means are per column within each",
        r"  block, computed from unrounded scores.}",
        r"  \label{tab:gsr_attrs_off}",
        r"  \small",
        r"  \begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}lrrr@{}}",
        r"    \toprule",
        r"    Half & DetA & AssA & LocA \\",
        r"    \midrule",
        r"    \multicolumn{4}{@{}l}{\emph{First 30\,s, all twenty halves}} \\",
    ]
    for m in MATCHES:
        for h in HALVES:
            lines.append(f"    {m}, {h}{mark(m)} & " + fmt(off30[(m, h)]) + r" \\")
    lines += [
        f"    Mean, all {NUMBER_WORDS.get(n30, n30)} halves & " + fmt(mean_off30) + r" \\",
        r"    \midrule",
        r"    \multicolumn{4}{@{}l}{\emph{Full half (45\,min), match-length evaluation set}} \\",
    ]
    for m, h in test + extra:
        lines.append(f"    {m}, {h}{mark(m)} & "
                     + fmt([full[(m, h)][k] for k in OFF_METRICS]) + r" \\")
    lines += [
        f"    Mean, all {NUMBER_WORDS.get(nfull, nfull)} halves & " + fmt(mean_offfull) + r" \\",
        r"    \bottomrule",
        r"  \end{tabular*}",
        r"\end{table}",
    ]
    OUT_OFF_TEX.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_OFF_TEX}")
    print("30s attrs-off means: " + ", ".join(
        f"{k}={v:.2f}" for k, v in zip(("deta", "assa", "loca"), mean_off30)))
    print("full attrs-off means: " + ", ".join(
        f"{k}={v:.2f}" for k, v in zip(OFF_METRICS, mean_offfull)))


def main():
    sweep = load_sweep()
    full = load_full()
    off30 = load_off30()
    emit_30s(sweep)
    emit_full(full)
    emit_attrs_off(off30, full)


if __name__ == "__main__":
    main()
